### ISSUE TITLE
Is there any way to make custom response?

### ISSUE THREAD

**Issue by matthew-cupist** [bauerji/flask-pydantic#45]
Hello! Thanks for awesome package.

I want to make custom response

ASIS
```
{
  "validation_error": {
    "query_params": [
      {
        "loc": ["age"],
        "msg": "value is not a valid integer",
        "type": "type_error.integer"
      }
    ]
  }
}
```
TOBE(or some other fomat, maybe)
```
{"error" : "validation_error", 
"desc" : "some_my_custome_message"}
```

Thanks for reading this.

**Comment by yogeshExplore** [comment]
+1 
I don't see any way to do this  in the current verison

**Comment by jcreekmore** [comment]
So, I have been thinking about this one and wanted to throw out an idea. There already exists the FLASK_PYDANTIC_VALIDATION_ERROR_STATUS_CODE configuration value that lets you change what the status code is. What if we added another configuration value like FLASK_PYDANTIC_VALIDATION_ERROR_EXCEPTION that, if set to true, would just raise an exception (to be defined) containing the fields that are in the current json error response. If the user set that config value, it is their responsibility to set the flask exception handler for that exception type, then they can return whatever type of response they want.
